FormosBar/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FormosBar.Controllers
{
    public class CartController : Controller
    {
        //GET Cart
        public ActionResult GetCart()
        {
            return PartialView("_PartialCart");
        }


        //Add Item to Cart
        public ActionResult AddToCart(int id)
        {
            var currentCart = Models.ShoppingCart.CartActions.CurrentShoppingCart();
            currentCart.AddProduct(id);
            return PartialView("_PartialCart");
        }

        //Remove Item From Cart
        public ActionResult RemoveFromCart(int id)
        {
            var currentCart = Models.ShoppingCart.CartActions.CurrentShoppingCart();
            currentCart.RemoveProduct(id);
            return PartialView("_PartialCart");
        }

        //Clear All Item From Cart
        public ActionResult ClearCart()
        {
            var currentCart = Models.ShoppingCart.CartActions.CurrentShoppingCart();
            currentCart.ClearCart();
            return PartialView("_PartialCart");
        }
    }
}

FormosBar/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FormosBar.Controllers
{
    public class ItemController : Controller
    {
        // GET: Item
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            //echo the Item List
            List<Models.Item> result = new List<Models.Item>();

            //handle the message
            ViewBag.Message = TempData["Message"];

            using (DAL.BarContext db = new DAL.BarContext())
            {
                result = (from s in db.Items select s).ToList();
                return View(result);
            }
        }

        //Create Item
        [Authorize(Roles ="Admin")]
        public ActionResult Create()
        {
            return View();
        }

        //Create Item Page - Data Post Back
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Create(Models.Item postback)
        {
            if (this.ModelState.IsValid)
            {
                using (DAL.BarContext db = new DAL.BarContext())
                {
                    //Post back data and add to Item table
                    db.Items.Add(postback);

                    //Save Change
                    db.SaveChanges();

                    //Item Create Sucessfully 
                    TempData["Message"] = String.Format("Item[{0}] is created", postback.Name);

                    return RedirectToAction("Index");
                }
            }
            else {
                ViewBag.Message = "The data entry is not correct.";
                return View(postback);
            }
            
        }

        //Edit Item Page
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            using (DAL.BarContext db = new DAL.BarContext())
            {
                //Catch Item.Id as Entry
                var result = (from s in db.Items where s.Id == id select s).FirstOrDefault();
                //verify the id
                if (result != default(Models.Item)) 
                {
                    return View(result); 
                }
                else
                {   //If no data is found, direct to Index
                    TempData["Message"] = "Please Input Again";
                    return RedirectToAction("Index");
                }
            }
        }

        //Edit Item Page
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(Models.Item postback)
        {
            //verify the user input
            if (this.ModelState.IsValid) 
            {
                using (DAL.BarContext db = new DAL.BarContext())
                {
                    //catch Item.Id and postback the data of Id
                    var result = (from s in db.Items where s.Id == postback.Id select s).FirstOrDefault();

                    //Save the change into Database
                    result.Name = postback.Name; result.Price = postback.Price;
                    result.Description = postback.Description; result.OnShelf = postback.OnShelf;
                    result.DefaultImageURL = postback.DefaultImageURL; result.Category = postback.Category;
                    result.ImageAlt = postback.ImageAlt;

                    //Save the change
                    db.SaveChanges();

                    //Pop-up "edit successfully" msg and direct to Index
                    TempData["Message"] = String.Format("Item [{0}] is edited ", postback.Name);
                    return RedirectToAction("Index");
                }
            }
            else
            {
                return View(postback);
            }
        }
    }
}

FormosBar/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using FormosBar.Models;
using FormosBar.Migrations.ContextB;
using Microsoft.AspNet.Identity;
using Order = FormosBar.Models.Order;
using OrderDetail = FormosBar.Models.OrderDetail;
using System.Data.Entity;

namespace FormosBar.Controllers
{
    public class OrderController : Controller
    {
        // GET: Order
        [Authorize(Roles = "Customer")]
        public ActionResult Index()
        {
            return View();
        }

        //Add Order to DB and Add Related Order Detail to DB
        [Authorize(Roles = "Customer")]
        [HttpPost]
        public ActionResult Index(Models.OrderLocation postback, Nullable <int> OrderId)
        {
            if (OrderId == null)
            {
                if (this.ModelState.IsValid)
                {
                    var currentcart = Models.ShoppingCart.CartActions.CurrentShoppingCart();
                    var userId = HttpContext.User.Identity.GetUserId();
                    var userName = HttpContext.User.Identity.GetUserName();

                    using (DAL.BarContext db = new DAL.BarContext())
                    {

                        var order = new Models.Order()
                        {
                            UserId = userId,
                            UserName = userName,
                            TableNumber = postback.TableNumber,
                        };

                        db.Orders.Add(order);
                        db.SaveChanges();

                        var orderDetails = currentcart.ToOrderDetailList(order.Id);

                        db.OrderDetails.AddRange(orderDetails);
                        db.SaveChanges();

                    }

                    return View("~/Views/Home/Index.cshtml");
                }
            }

            //Handle Add-on Item
            else
            {

                if (this.ModelState.IsValid)
                {
                    var currentcart = Models.ShoppingCart.CartActions.CurrentShoppingCart();

                    using (DAL.BarContext db = new DAL.BarContext())
                    {

                        var orderDetails = currentcart.ToOrderDetailList(OrderId.GetValueOrDefault());

                        db.OrderDetails.AddRange(orderDetails);
                        db.SaveChanges();

                    }

                    return View("~/Views/Home/Index.cshtml");
                }

            }
            return View();
        }

        //Customer View Own Order
        [Authorize(Roles = "Customer")]
        public ActionResult YourOrder()
        {
            var userId = HttpContext.User.Identity.GetUserId();

            using (DAL.BarContext db = new DAL.BarContext())
            {
                var result = (from s in db.Orders
                              where s.UserId == userId
                              select s).ToList();

                return View(result);
            }
        }

        //Customer View Own Order Detail
        [Authorize(Roles = "Customer")]
        public ActionResult YourOrderDetail(int id)
        {
            using (DAL.BarContext db = new DAL.BarContext())
            {
                var result = (from s in db.OrderDetails
                              where s.OrderId == id
                              select s).ToList();

                if (result.Count == 0)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(result);
                }
            }
        }

        //Customer Delete Own Order
        [Authorize(Roles = "Customer")]
        public async Task<ActionResult> Delete(int? id)
        {
            using (DAL.BarContext db = new DAL.BarContext()) { 
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
            Order order = await db.Orders.FindAsync(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
            }
        }

        [Authorize(Roles = "Customer")]
        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            using (DAL.BarContext db = new DAL.BarContext())
            {

                Order order = await db.Orders.FindAsync(id);
                db.Orders.Remove(order);
                await db.SaveChangesAsync();
                return RedirectToAction("YourOrder");
            }
        }




















        public ActionResult Add()
        {
            return View();
        }

        //Create Item Page - Data Post Back
        [HttpPost]
        public ActionResult Add(Models.OrderDetail postback)
        {
            if (this.ModelState.IsValid)
            {
                using (DAL.BarContext db = new DAL.BarContext())
                {
                    //Post back data and add to Item table
                    db.OrderDetails.Add(postback);

                    //Save Change
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
            }
            else
            {
                ViewBag.Message = "The data entry is not correct.";
                return View(postback);
            }

        }









        //public async Task<ActionResult> Edit(int? id)
        //{
        //    using (DAL.BarContext db = new DAL.BarContext())
        //    {

        //        if (id == null)
        //        {
        //            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //        }
        //        OrderDetail orderdetail = await db.OrderDetails.FindAsync(id);
        //        if (orderdetail == null)
        //        {
        //            return HttpNotFound();
        //        }
        //        return View(orderdetail);
        //    }
        //}

        //// POST: Orders/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> Edit(OrderDetail orderdetail)
        //{
        //    using (DAL.BarContext db = new DAL.BarContext())
        //    {
        //        if (ModelState.IsValid)
        //        {
        //            db.Entry(orderdetail).State = EntityState.Modified;
        //            await db.SaveChangesAsync();
        //            return RedirectToAction("Index");
        //        }
        //        return View(orderdetail);
        //    }
        //}

    }
}

FormosBar/Controllers/OrderManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace FormosBar.Controllers
{
    [Authorize(Roles = "Admin")]
    public class OrderManagerController : Controller
    {
        // GET: OrderManager
        public ActionResult Index()
        {
            using (DAL.BarContext db = new DAL.BarContext())
            {
                var result = (from s in db.Orders
                              select s).ToList();

                return View(result);
            }
        }

        //Admin View Order Details
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int id)
        {
            using (DAL.BarContext db = new DAL.BarContext())
            {
                var result = (from s in db.OrderDetails
                              where s.OrderId == id
                              select s).ToList();

                if (result.Count == 0)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(result);
                }
            }
        }

        //Admin View Order Details by Searching Function
        public ActionResult SerachByUserName(string UserName)
        {
            //string searchUserId = null;

            var userName = UserName;


            using (DAL.BarContext db = new DAL.BarContext())
            {
                var userId = HttpContext.User.Identity.GetUserId();

                //searchUserId = (from s in db.AspNetUsers
                //                where s.UserName == UserName
                //                select s.Id).FirstOrDefault();
            }
            if (!String.IsNullOrEmpty(userName))
            {
                using (DAL.BarContext db = new DAL.BarContext())
                {
                    var result = (from s in db.Orders
                                  where s.UserName == userName
                                  select s).ToList();

                    return View("Index", result);
                }
            }
            else
            {  
                return View("Index", new List<Models.Order>());
            }

        }
    }
}

FormosBar/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title | FormosBar - Chill & Full</title>

    <script src="http://code.jquery.com/jquery-1.8.3.js"></script>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">



</head>
<body style="background-image:url(../../Content/img/bg.png); background-size: 27%; background-repeat: repeat;">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" role="button" aria-disabled="false" aria-describedby="Navigation Bar" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(" ", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Menu", "Menu", "Home")</li>
                    <li>@Html.ActionLink("Product Management", "Index", "Item")</li>
                    <li>@Html.ActionLink("Order Management", "Index", "OrderManager")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()

        <button onclick="topFunction()" id="back2top" title="Go to top">Top</button>
        <hr />


    </div>
    <footer class="navbar-fixed-bottom" style="padding:0px; margin:0; position:fixed; bottom:0">
        <div class="modal-footer">
            <div class="footer-container-left">&copy; @DateTime.Now.Year FormosBar. &emsp; |&emsp; Privacy Policy&emsp; |&emsp; Terms of Use&emsp;|&emsp;Accessibility Statement&emsp;|</div>
            <div class="footer-container-right">
                <b><font color="#b6ff00">Follow Us <i class="glyphicon glyphicon-chevron-right"></i></font></b>&nbsp;
                <a href="#" class="fa fa-facebook"></a>
                <a href="#" class="fa fa-twitter"></a>
                <a href="#" class="fa fa-youtube"></a>
            </div>
            <div class="footer-container-slogan">
                <img src="~/Content/img/Slogan.png" alt="Bar Slogan" title="Bar Slogan" style="max-width: 150px;" />
            </div>
        </div>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

FormosBar/Views/Shared/_CustomerLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title | FormosBar - Chill & Full</title>


    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <script type="text/javascript">
        $(document).ready(function () {
            console.log("ready!");
        });

        function AddToCart(productId) {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("AddToCart", "Cart")',
                data: { id: productId }
            })
            .done(function (msg) {
                $('li#Cart').html(msg);
                });
        }

        function RemoveFromCart(productId) {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("RemoveFromCart", "Cart")',
                data: { id: productId }
            })
            .done(function (msg) {
                $('li#Cart').html(msg);
            });
        }


        function ClearCart() {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("ClearCart", "Cart")',
                data: {}
            })
            .done(function (msg) {
                $('li#Cart').html(msg);
            });
        }

    </script>


</head>
<body style="background-image:url(../../Content/img/bg.png); background-size: 27%; background-repeat: repeat;">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" role="button" aria-disabled="false" aria-describedby="Navigation Bar" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(" ", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About Us", "About", "Home")</li>
                    <li>@Html.ActionLink("Menu", "Menu", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <button onclick="topFunction()" id="back2top" title="Go to top">Top</button>

        <hr />
    </div>
    <footer class="navbar-fixed-bottom" style="padding:0px; margin:0; position:fixed; bottom:0">
        <div class="modal-footer">
            <div class="footer-container-left">&copy; @DateTime.Now.Year FormosBar. &emsp; |&emsp; Privacy Policy&emsp; |&emsp; Terms of Use&emsp;|&emsp;Accessibility Statement&emsp;|</div>
            <div class="footer-container-right">
                <b><font color="#b6ff00">Follow Us <i class="glyphicon glyphicon-chevron-right"></i></font></b>&nbsp;
                <a href="#" class="fa fa-facebook"></a>
                <a href="#" class="fa fa-twitter"></a>
                <a href="#" class="fa fa-youtube"></a>
            </div>
            <div class="footer-container-slogan">
                <img src="~/Content/img/Slogan.png" alt="Bar Slogan" title="Bar Slogan" style="max-width: 150px;" />
            </div>
        </div>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

FormosBar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title | FormosBar - Chill & Full</title>


    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


</head>
<body style="background-image:url(../../Content/img/bg.png); background-size: 27%; background-repeat: repeat;">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" role="button" aria-disabled="false" aria-describedby="Navigation Bar" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(" ", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About Us", "About", "Home")</li>
                    <li>@Html.ActionLink("Menu","Menu", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <button onclick="topFunction()" id="back2top" title="Go to top">Top</button>

        <hr />
    </div>
<footer class="navbar-fixed-bottom" style="padding:0px; margin:0; position:fixed; bottom:0">
        <div class="modal-footer">
            <div class="footer-container-left">&copy; @DateTime.Now.Year FormosBar. &emsp; |&emsp; Privacy Policy&emsp; |&emsp; Terms of Use&emsp;|&emsp;Accessibility Statement&emsp;|</div>
            <div class="footer-container-right">
                <b><font color="#b6ff00">Follow Us <i class="glyphicon glyphicon-chevron-right"></i></font></b>&nbsp;
                <a href="#" class="fa fa-facebook"></a>
                <a href="#" class="fa fa-twitter"></a>
                <a href="#" class="fa fa-youtube"></a>
            </div>
            <div class="footer-container-slogan">    
                <img src="~/Content/img/Slogan.png" alt="Bar Slogan" title="Bar Slogan" style="max-width: 150px;" />
            </div>
        </div>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

FormosBar/Views/Shared/_PartialCart.cshtml
@{
    var currentCart = FormosBar.Models.ShoppingCart.CartActions.CurrentShoppingCart();
}
<a id="CartDropDown" class="dropdown-toggle" data-toggle="dropdown">
    @String.Format("Total: £{0} ({1})", currentCart.TotalAmount, currentCart.Count)
    <span class="caret"></span>
</a>
<ul class="dropdown-menu" role="menu" aria-labelledby="CartDropDown">
    @if (currentCart.Count > 0)
    {
        foreach (var cartitem in currentCart)
        {
    <li class="CartLi">
        @{
            int result = cartitem.Quantity * cartitem.Price;
        }
        <span class="CartCancel btn btn-danger " onclick="RemoveFromCart('@cartitem.Id')">X</span>
        <span class="CartSpanQuantity">@cartitem.Quantity</span><span>x &pound;@cartitem.Price <b>(&pound;@result)</b></span><span class="CartSpanName">@cartitem.Name</span>
    </li>
        }
        <li class="divider"></li>
        <li>
            <div id="CartButtons" role="button" aria-disabled="false" aria-describedby="Check Out Option">
                <a class="btn btn-success text-center CartActionButtom" href="@Url.Action("Index","Order",new { })">CheckOut</a>
                <a class="btn btn-danger text-center CartActionButtom" onclick="ClearCart()">Clear</a>
            </div>
        </li>

    }
    else
    {
        <li><a class="text-center"><b>No Items At Cart</b></a></li>
    }
</ul>